version: '2.3'

services:
  pa-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: pa-ai
    container_name: pa-ai-container
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
      MKL_SERVICE_FORCE_INTEL: "1"
      TORCH_USE_CUDA_DSA: "1"
      CUDA_LAUNCH_BLOCKING: "1"
      TRANSFORMERS_CACHE: "/app/shared/huggingface"
      # OPENAI_API_KEY: "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"
    ports:
      - "8000:80"
    volumes:
      - ./datasets:/app/datasets
      - ./output:/app/output
      - ./shared:/app/shared
    runtime: nvidia
    networks:
      - pa-ai-network

networks:
  pa-ai-network:
    external: true