version: '2.3'

services:
  pa-ai:
    build:
      context: ./generative-module
      dockerfile: Dockerfile
    image: pa-ai
    container_name: pa-ai-container
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
      MKL_SERVICE_FORCE_INTEL: "1"
      TORCH_USE_CUDA_DSA: "1"
      CUDA_LAUNCH_BLOCKING: "1"
      HF_HOME: "/app/shared/huggingface"
    ports:
      - "8000:80"
    volumes:
      - ./datasets:/app/datasets
      - ./output:/app/output
      - ./shared:/app/shared
    runtime: nvidia
    networks:
      - pa-ai-network

  streamlit:
    build:
      context: ./streamlit-module
      dockerfile: Dockerfile
    container_name: pa-ai-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./datasets:/app/datasets
      - ./output:/app/output
      - ./shared:/app/shared
    depends_on:
      - pa-ai
    networks:
      - pa-ai-network

networks:
  pa-ai-network:
    external: true